[package]
name = "diffie-hellman"
version = "0.1.0"
authors = [""]

[dependencies]
num = "0.1"
rand = "0.3.14"
hmac = "0.5"
sha3 = "0.7.3"
sha2 = "0.7"
chrono = "0.4.3"
proptest = "0.7.1"
digest = "0.7.4"

